sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"

matrix:
  include:
  - ghc: 8.6.5
  - ghc: 8.8.4
  - ghc: 8.10.2

install:
  - ghc --version
  - cabal --version
  - cabal update
  - cabal build --enable-tests --enable-benchmarks

script:
  - cabal test --enable-tests

notifications:
  email: false
