name: Test & Publish

on:
  push:
    tags:
      - 'release-v[0-9]+.[0-9]+.[0-9]+.[0-9]+'
    branches:
      - new
      - work
      - main

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        ghc: ["9.0.1"]
        cabal: ["3.4"]

    runs-on: ${{ matrix.os }}

    steps:
      - id: haskell
        name: Haskell Setup
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Valor Checkout
        uses: actions/checkout@v2

      - name: Cabal Update
        run: cabal v2-update

      - name: Cabal Freeze
        run: cabal v2-freeze

      - name: Caching
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.haskell.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles( 'cabal.project.freeze' ) }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}

      - name: Building
        run: cabal v2-build all

      - name: Testing
        run: cabal v2-test all --test-show-details=direct

      - name: Documenting
        run: cabal v2-haddock

      - name: Publishing to Hackage
        if: startsWith( github.ref , '/refs/tags/release-' )
        run: echo "Published!"
